# Generated by Django 5.0.6 on 2024-05-16 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(max_length=250),
        ),
    ]
