# Generated by Django 5.0.6 on 2024-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_form', '0002_uploadedfile_file_id_alter_uploadedfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_describe',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
